#!/usr/bin/env perl

use strict;
use warnings;

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application

Mojolicious::Commands->start_app('Mgmt::Service', 'daemon', '-m', 'production', '-l', 'http://127.0.0.1:3000');
